services:
  - type: web
    name: fhir-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.pryyjegotiquslrprjmn
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://fhirfly.me,https://www.fhirfly.me,https://*.vercel.app,http://localhost:3000"

